## classifier 

In [1]:
from sklearn.ensemble import RandomForestClassifier

## 변수를 임으로 clf로 지정하고 여러변수 중에 random_state를 0으로 설정함
## 0이 아니라도 뭐든 지정가능.. 이게 다르면 같은 결과값이 안나옴
clf = RandomForestClassifier(random_state=0)
X = [[1, 2, 3],[11, 12, 13]]
## 여기는 독립변수가 2개라서 종속도 2개 준거
y = [0, 1]
## fit이라는 모델로 학습을 시키겠다 X는 독립변수 , Y는 종속변수
clf.fit(X,y)

RandomForestClassifier(random_state=0)

In [2]:
## 여기는 내가 넣은 독립변수랑 모양이 같아야함
clf.predict(X)

array([0, 1])

In [3]:
## 여기는 내가 넣은 독립변수 X랑 모양이 같아야함, 즉 X가 X=[[]]니까 [[]]형태로 넣기
clf.predict([[234, 23, 456]])

array([1])

In [4]:
import numpy as np

In [9]:
##여기도 RandomState를 10으로 줘서..몇번재실행해도 같은 결과 나오는거!
rs = np.random.RandomState(10)
## 임의의난수를 5개 만들어라 rand(5)
x = 10*rs.rand(12)
## y에도 난수를 곱해서 빼줘서 임의의수를 만들어냄 
y = 2*x - 1*rs.rand(12)
x.shape, y.shape

((12,), (12,))

In [12]:
x

array([7.71320643, 0.20751949, 6.33648235, 7.48803883, 4.98507012,
       2.24796646, 1.98062865, 7.60530712, 1.69110837, 0.88339814,
       6.85359818, 9.53393346])

In [23]:
## 지금 위에 x는 그냥 12개 값이 이어지는데 그걸 행열로 맞출려고 3*4이라고 씀
## 혹은 (-1,4)라고 적으면 자동으로 3*4를 만들어줌, 해석하면 뒤는 4로 앞은 알아서해줘 (-1)
X = x.reshape(-1,4)
X.shape

(3, 4)

In [24]:
X

array([[7.71320643, 0.20751949, 6.33648235, 7.48803883],
       [4.98507012, 2.24796646, 1.98062865, 7.60530712],
       [1.69110837, 0.88339814, 6.85359818, 9.53393346]])